image: andreysenov/firebase-tools

stages:
  - build
  - deploy

build:
  environment: test
  stage: build
  script:
    - npm run setup
    - npm run build:dev
  except:
    - master

deploy-dev:
  environment: test
  stage: deploy
  only:
    - master
  variables:
    APP_ENV: $APP_ENV_DEV
    FIREBASE_API_KEY: $FIREBASE_API_KEY_DEV
    FIREBASE_DATABASE_NAME: $FIREBASE_DATABASE_NAME_DEV
    FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID_DEV
    FIREBASE_SENDER_ID: $FIREBASE_SENDER_ID_DEV
  script:
    - npm run setup
    - firebase use develop --token $FIREBASE_TOKEN
    - firebase deploy -m "Deploying to test environment" --token $FIREBASE_TOKEN

deploy-prod:
  environment: production
  stage: deploy
  only:
    - tags
  variables:
    APP_ENV: $APP_ENV_PROD
    FIREBASE_API_KEY: $FIREBASE_API_KEY_PROD
    FIREBASE_DATABASE_NAME: $FIREBASE_DATABASE_NAME_PROD
    FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID_PROD
    FIREBASE_SENDER_ID: $FIREBASE_SENDER_ID_PROD
  script:
    - npm run setup
    - firebase use production --token $FIREBASE_TOKEN
    - firebase deploy -m "Deploying to production environment" --token $FIREBASE_TOKEN
